FROM golang:1.21-alpine3.20 AS builder

WORKDIR  /usr/src/app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o desafio main.go

FROM scratch

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/desafio .

ENTRYPOINT ["./desafio"]